// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: auth.proto

package authv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AuthService_ValidateAPIKey_FullMethodName        = "/auth.v1.AuthService/ValidateAPIKey"
	AuthService_ValidateWSToken_FullMethodName       = "/auth.v1.AuthService/ValidateWSToken"
	AuthService_GetClientEntitlements_FullMethodName = "/auth.v1.AuthService/GetClientEntitlements"
	AuthService_CheckClientStatus_FullMethodName     = "/auth.v1.AuthService/CheckClientStatus"
)

// AuthServiceClient is the client API for AuthService service.
type AuthServiceClient interface {
	ValidateAPIKey(ctx context.Context, in *ValidateAPIKeyRequest, opts ...grpc.CallOption) (*ValidateAPIKeyResponse, error)
	ValidateWSToken(ctx context.Context, in *ValidateWSTokenRequest, opts ...grpc.CallOption) (*ValidateWSTokenResponse, error)
	GetClientEntitlements(ctx context.Context, in *GetClientEntitlementsRequest, opts ...grpc.CallOption) (*GetClientEntitlementsResponse, error)
	CheckClientStatus(ctx context.Context, in *CheckClientStatusRequest, opts ...grpc.CallOption) (*CheckClientStatusResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) ValidateAPIKey(ctx context.Context, in *ValidateAPIKeyRequest, opts ...grpc.CallOption) (*ValidateAPIKeyResponse, error) {
	out := new(ValidateAPIKeyResponse)
	err := c.cc.Invoke(ctx, AuthService_ValidateAPIKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ValidateWSToken(ctx context.Context, in *ValidateWSTokenRequest, opts ...grpc.CallOption) (*ValidateWSTokenResponse, error) {
	out := new(ValidateWSTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_ValidateWSToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetClientEntitlements(ctx context.Context, in *GetClientEntitlementsRequest, opts ...grpc.CallOption) (*GetClientEntitlementsResponse, error) {
	out := new(GetClientEntitlementsResponse)
	err := c.cc.Invoke(ctx, AuthService_GetClientEntitlements_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CheckClientStatus(ctx context.Context, in *CheckClientStatusRequest, opts ...grpc.CallOption) (*CheckClientStatusResponse, error) {
	out := new(CheckClientStatusResponse)
	err := c.cc.Invoke(ctx, AuthService_CheckClientStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	ValidateAPIKey(context.Context, *ValidateAPIKeyRequest) (*ValidateAPIKeyResponse, error)
	ValidateWSToken(context.Context, *ValidateWSTokenRequest) (*ValidateWSTokenResponse, error)
	GetClientEntitlements(context.Context, *GetClientEntitlementsRequest) (*GetClientEntitlementsResponse, error)
	CheckClientStatus(context.Context, *CheckClientStatusRequest) (*CheckClientStatusResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) ValidateAPIKey(context.Context, *ValidateAPIKeyRequest) (*ValidateAPIKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateAPIKey not implemented")
}
func (UnimplementedAuthServiceServer) ValidateWSToken(context.Context, *ValidateWSTokenRequest) (*ValidateWSTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateWSToken not implemented")
}
func (UnimplementedAuthServiceServer) GetClientEntitlements(context.Context, *GetClientEntitlementsRequest) (*GetClientEntitlementsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientEntitlements not implemented")
}
func (UnimplementedAuthServiceServer) CheckClientStatus(context.Context, *CheckClientStatusRequest) (*CheckClientStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckClientStatus not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_ValidateAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ValidateAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ValidateAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ValidateAPIKey(ctx, req.(*ValidateAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ValidateWSToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateWSTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ValidateWSToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ValidateWSToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ValidateWSToken(ctx, req.(*ValidateWSTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetClientEntitlements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientEntitlementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetClientEntitlements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetClientEntitlements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetClientEntitlements(ctx, req.(*GetClientEntitlementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CheckClientStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckClientStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CheckClientStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CheckClientStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CheckClientStatus(ctx, req.(*CheckClientStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateAPIKey",
			Handler:    _AuthService_ValidateAPIKey_Handler,
		},
		{
			MethodName: "ValidateWSToken",
			Handler:    _AuthService_ValidateWSToken_Handler,
		},
		{
			MethodName: "GetClientEntitlements",
			Handler:    _AuthService_GetClientEntitlements_Handler,
		},
		{
			MethodName: "CheckClientStatus",
			Handler:    _AuthService_CheckClientStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
