// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.1
// source: auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawApiKey     string                 `protobuf:"bytes,1,opt,name=raw_api_key,json=rawApiKey,proto3" json:"raw_api_key,omitempty"`
	RequiredScope string                 `protobuf:"bytes,2,opt,name=required_scope,json=requiredScope,proto3" json:"required_scope,omitempty"`
	SportId       int32                  `protobuf:"varint,3,opt,name=sport_id,json=sportId,proto3" json:"sport_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAPIKeyRequest) Reset() {
	*x = ValidateAPIKeyRequest{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAPIKeyRequest) ProtoMessage() {}

func (x *ValidateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ValidateAPIKeyRequest) GetRawApiKey() string {
	if x != nil {
		return x.RawApiKey
	}
	return ""
}

func (x *ValidateAPIKeyRequest) GetRequiredScope() string {
	if x != nil {
		return x.RequiredScope
	}
	return ""
}

func (x *ValidateAPIKeyRequest) GetSportId() int32 {
	if x != nil {
		return x.SportId
	}
	return 0
}

type ValidateAPIKeyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Valid          bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	ClientId       string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientName     string                 `protobuf:"bytes,3,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	Plan           string                 `protobuf:"bytes,4,opt,name=plan,proto3" json:"plan,omitempty"`
	Environment    string                 `protobuf:"bytes,5,opt,name=environment,proto3" json:"environment,omitempty"`
	Scopes         []string               `protobuf:"bytes,6,rep,name=scopes,proto3" json:"scopes,omitempty"`
	AllowedSports  []int32                `protobuf:"varint,7,rep,packed,name=allowed_sports,json=allowedSports,proto3" json:"allowed_sports,omitempty"`
	KeyId          string                 `protobuf:"bytes,8,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	ExpiresAtUnix  int64                  `protobuf:"varint,9,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorCode      string                 `protobuf:"bytes,11,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidateAPIKeyResponse) Reset() {
	*x = ValidateAPIKeyResponse{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAPIKeyResponse) ProtoMessage() {}

func (x *ValidateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ValidateAPIKeyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateAPIKeyResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ValidateAPIKeyResponse) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *ValidateAPIKeyResponse) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *ValidateAPIKeyResponse) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ValidateAPIKeyResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *ValidateAPIKeyResponse) GetAllowedSports() []int32 {
	if x != nil {
		return x.AllowedSports
	}
	return nil
}

func (x *ValidateAPIKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ValidateAPIKeyResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *ValidateAPIKeyResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ValidateAPIKeyResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type ValidateWSTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateWSTokenRequest) Reset() {
	*x = ValidateWSTokenRequest{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateWSTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateWSTokenRequest) ProtoMessage() {}

func (x *ValidateWSTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ValidateWSTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateWSTokenResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Valid          bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	ClientId       string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientName     string                 `protobuf:"bytes,3,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	Plan           string                 `protobuf:"bytes,4,opt,name=plan,proto3" json:"plan,omitempty"`
	Environment    string                 `protobuf:"bytes,5,opt,name=environment,proto3" json:"environment,omitempty"`
	Scopes         []string               `protobuf:"bytes,6,rep,name=scopes,proto3" json:"scopes,omitempty"`
	AllowedSports  []int32                `protobuf:"varint,7,rep,packed,name=allowed_sports,json=allowedSports,proto3" json:"allowed_sports,omitempty"`
	KeyId          string                 `protobuf:"bytes,8,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	ExpiresAtUnix  int64                  `protobuf:"varint,9,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorCode      string                 `protobuf:"bytes,11,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidateWSTokenResponse) Reset() {
	*x = ValidateWSTokenResponse{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateWSTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateWSTokenResponse) ProtoMessage() {}

func (x *ValidateWSTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ValidateWSTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateWSTokenResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ValidateWSTokenResponse) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *ValidateWSTokenResponse) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *ValidateWSTokenResponse) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ValidateWSTokenResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *ValidateWSTokenResponse) GetAllowedSports() []int32 {
	if x != nil {
		return x.AllowedSports
	}
	return nil
}

func (x *ValidateWSTokenResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ValidateWSTokenResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *ValidateWSTokenResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ValidateWSTokenResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type GetClientEntitlementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientEntitlementsRequest) Reset() {
	*x = GetClientEntitlementsRequest{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientEntitlementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientEntitlementsRequest) ProtoMessage() {}

func (x *GetClientEntitlementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetClientEntitlementsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type GetClientEntitlementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Plan          string                 `protobuf:"bytes,3,opt,name=plan,proto3" json:"plan,omitempty"`
	Scopes        []string               `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	AllowedSports []int32                `protobuf:"varint,5,rep,packed,name=allowed_sports,json=allowedSports,proto3" json:"allowed_sports,omitempty"`
	RateLimitRpm  int32                  `protobuf:"varint,6,opt,name=rate_limit_rpm,json=rateLimitRpm,proto3" json:"rate_limit_rpm,omitempty"`
	IpAllowlist   []string               `protobuf:"bytes,7,rep,name=ip_allowlist,json=ipAllowlist,proto3" json:"ip_allowlist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientEntitlementsResponse) Reset() {
	*x = GetClientEntitlementsResponse{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientEntitlementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientEntitlementsResponse) ProtoMessage() {}

func (x *GetClientEntitlementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetClientEntitlementsResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GetClientEntitlementsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetClientEntitlementsResponse) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *GetClientEntitlementsResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *GetClientEntitlementsResponse) GetAllowedSports() []int32 {
	if x != nil {
		return x.AllowedSports
	}
	return nil
}

func (x *GetClientEntitlementsResponse) GetRateLimitRpm() int32 {
	if x != nil {
		return x.RateLimitRpm
	}
	return 0
}

func (x *GetClientEntitlementsResponse) GetIpAllowlist() []string {
	if x != nil {
		return x.IpAllowlist
	}
	return nil
}

type CheckClientStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckClientStatusRequest) Reset() {
	*x = CheckClientStatusRequest{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckClientStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckClientStatusRequest) ProtoMessage() {}

func (x *CheckClientStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CheckClientStatusRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type CheckClientStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsSuspended   bool                   `protobuf:"varint,4,opt,name=is_suspended,json=isSuspended,proto3" json:"is_suspended,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckClientStatusResponse) Reset() {
	*x = CheckClientStatusResponse{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckClientStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckClientStatusResponse) ProtoMessage() {}

func (x *CheckClientStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CheckClientStatusResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CheckClientStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CheckClientStatusResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CheckClientStatusResponse) GetIsSuspended() bool {
	if x != nil {
		return x.IsSuspended
	}
	return false
}

func (x *CheckClientStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}
