package market

import (
	"strconv"
	"strings"
	"sync"
)

var (
	catalogueMu sync.RWMutex
	catalogue   = make(map[string]MarketDefinition)
)

func init() {
	// Register all canonical market definitions across the 12 active sports
	defs := []MarketDefinition{
		// --------------------------------------------------------------------
		// 1. FOOTBALL (SportID 1)
		// --------------------------------------------------------------------
		{
			SportID:              1,
			MarketCode:           "FB_1X2",
			MarketName:           "1X2 / Match Result",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "X", "2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              1,
			MarketCode:           "FB_TOTAL_GOALS",
			MarketName:           "Total Goals Over/Under",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"OVER", "UNDER"},
			HasLine:              true,
			LineType:             "DECIMAL",
			Status:               MarketStatusActive,
		},
		{
			SportID:              1,
			MarketCode:           "FB_BTTS",
			MarketName:           "Both Teams To Score",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"YES", "NO"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              1,
			MarketCode:           "FB_DOUBLE_CHANCE",
			MarketName:           "Double Chance",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1X", "12", "X2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              1,
			MarketCode:           "FB_DNB",
			MarketName:           "Draw No Bet",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              1,
			MarketCode:           "FB_ASIAN_HANDICAP",
			MarketName:           "Asian Handicap",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			HasLine:              true,
			LineType:             "QUARTERS",
			Status:               MarketStatusActive,
		},
		{
			SportID:              1,
			MarketCode:           "FB_EUROPEAN_HANDICAP",
			MarketName:           "European Handicap",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "X", "2"},
			HasLine:              true,
			LineType:             "INTEGER",
			Status:               MarketStatusActive,
		},
		{
			SportID:              1,
			MarketCode:           "FB_CORRECT_SCORE",
			MarketName:           "Correct Score",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			Status:               MarketStatusActive,
		},
		{
			SportID:              1,
			MarketCode:           "FB_HT_1X2",
			MarketName:           "Half Time Result",
			Period:               PeriodHalfTime,
			RequiredResultDomain: DomainPeriodScore,
			SettlementTiming:     TimingPeriodEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "X", "2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              1,
			MarketCode:           "FB_TOTAL_GOALS",
			MarketName:           "Half Time Total Goals",
			Period:               PeriodHalfTime,
			RequiredResultDomain: DomainPeriodScore,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"OVER", "UNDER"},
			HasLine:              true,
			LineType:             "DECIMAL",
			Status:               MarketStatusActive,
		},
		{
			SportID:              1,
			MarketCode:           "FB_2H_1X2",
			MarketName:           "2nd Half Result",
			Period:               PeriodSecondHalf,
			RequiredResultDomain: DomainPeriodScore,
			SettlementTiming:     TimingPeriodEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "X", "2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              1,
			MarketCode:           "FB_TOTAL_GOALS",
			MarketName:           "2nd Half Total Goals",
			Period:               PeriodSecondHalf,
			RequiredResultDomain: DomainPeriodScore,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"OVER", "UNDER"},
			HasLine:              true,
			LineType:             "DECIMAL",
			Status:               MarketStatusActive,
		},
		{
			SportID:              1,
			MarketCode:           "FB_HT_FT",
			MarketName:           "Half Time / Full Time",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainPeriodScore,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			Status:               MarketStatusActive,
		},
		{
			SportID:              1,
			MarketCode:           "FB_ODD_EVEN",
			MarketName:           "Odd/Even Goals",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"ODD", "EVEN"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              1,
			MarketCode:           "FB_CLEAN_SHEET",
			MarketName:           "Clean Sheet",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"HOME", "AWAY"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              1,
			MarketCode:           "FB_WIN_TO_NIL",
			MarketName:           "Win To Nil",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              1,
			MarketCode:           "FB_HOME_TOTALS",
			MarketName:           "Home Team Total Goals",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"OVER", "UNDER"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              1,
			MarketCode:           "FB_AWAY_TOTALS",
			MarketName:           "Away Team Total Goals",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"OVER", "UNDER"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              1,
			MarketCode:           "FB_CORNERS_1X2",
			MarketName:           "Corners 1X2",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainCorners,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "X", "2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              1,
			MarketCode:           "FB_CORNERS_TOTAL",
			MarketName:           "Corners Total",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainCorners,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"OVER", "UNDER"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              1,
			MarketCode:           "FB_CARDS_TOTAL",
			MarketName:           "Cards Total",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainCards,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"OVER", "UNDER"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},

		// --------------------------------------------------------------------
		// 2. BASKETBALL (SportID 2)
		// --------------------------------------------------------------------
		{
			SportID:              2,
			MarketCode:           "BB_MONEYLINE",
			MarketName:           "Moneyline (incl. OT)",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			IncludesOvertime:     true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              2,
			MarketCode:           "BB_SPREAD",
			MarketName:           "Spread (incl. OT)",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			HasLine:              true,
			IncludesOvertime:     true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              2,
			MarketCode:           "BB_TOTAL_POINTS",
			MarketName:           "Total Points (incl. OT)",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"OVER", "UNDER"},
			HasLine:              true,
			IncludesOvertime:     true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              2,
			MarketCode:           "BB_TOTAL_POINTS",
			MarketName:           "1st Half Total Points",
			Period:               PeriodHalfTime,
			RequiredResultDomain: DomainPeriodScore,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"OVER", "UNDER"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              2,
			MarketCode:           "BB_1H_WINNER",
			MarketName:           "1st Half Winner",
			Period:               PeriodHalfTime,
			RequiredResultDomain: DomainPeriodScore,
			SettlementTiming:     TimingPeriodEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              2,
			MarketCode:           "BB_QUARTER_WINNER",
			MarketName:           "Q1 Winner",
			Period:               PeriodQuarter1,
			RequiredResultDomain: DomainPeriodScore,
			SettlementTiming:     TimingPeriodEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              2,
			MarketCode:           "BB_QUARTER_WINNER",
			MarketName:           "Q2 Winner",
			Period:               PeriodQuarter2,
			RequiredResultDomain: DomainPeriodScore,
			SettlementTiming:     TimingPeriodEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              2,
			MarketCode:           "BB_QUARTER_WINNER",
			MarketName:           "Q3 Winner",
			Period:               PeriodQuarter3,
			RequiredResultDomain: DomainPeriodScore,
			SettlementTiming:     TimingPeriodEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              2,
			MarketCode:           "BB_QUARTER_WINNER",
			MarketName:           "Q4 Winner",
			Period:               PeriodQuarter4,
			RequiredResultDomain: DomainPeriodScore,
			SettlementTiming:     TimingPeriodEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              2,
			MarketCode:           "BB_QUARTER_TOTALS",
			MarketName:           "Q1 Total Points",
			Period:               PeriodQuarter1,
			RequiredResultDomain: DomainPeriodScore,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"OVER", "UNDER"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              2,
			MarketCode:           "BB_QUARTER_TOTALS",
			MarketName:           "Q2 Total Points",
			Period:               PeriodQuarter2,
			RequiredResultDomain: DomainPeriodScore,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"OVER", "UNDER"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              2,
			MarketCode:           "BB_QUARTER_TOTALS",
			MarketName:           "Q3 Total Points",
			Period:               PeriodQuarter3,
			RequiredResultDomain: DomainPeriodScore,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"OVER", "UNDER"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              2,
			MarketCode:           "BB_QUARTER_TOTALS",
			MarketName:           "Q4 Total Points",
			Period:               PeriodQuarter4,
			RequiredResultDomain: DomainPeriodScore,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"OVER", "UNDER"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},

		// --------------------------------------------------------------------
		// 3. TENNIS (SportID 3)
		// --------------------------------------------------------------------
		{
			SportID:              3,
			MarketCode:           "TN_MATCH_WINNER",
			MarketName:           "Match Winner",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainSets,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              3,
			MarketCode:           "TN_SET_WINNER",
			MarketName:           "Set 1 Winner",
			Period:               PeriodSet1,
			RequiredResultDomain: DomainGames,
			SettlementTiming:     TimingPeriodEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              3,
			MarketCode:           "TN_SET_WINNER",
			MarketName:           "Set 2 Winner",
			Period:               PeriodSet2,
			RequiredResultDomain: DomainGames,
			SettlementTiming:     TimingPeriodEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              3,
			MarketCode:           "TN_SET_WINNER",
			MarketName:           "Set 3 Winner",
			Period:               PeriodSet3,
			RequiredResultDomain: DomainGames,
			SettlementTiming:     TimingPeriodEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              3,
			MarketCode:           "TN_TOTAL_GAMES",
			MarketName:           "Total Games Over/Under",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainGames,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"OVER", "UNDER"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              3,
			MarketCode:           "TN_GAME_HANDICAP",
			MarketName:           "Game Handicap",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainGames,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              3,
			MarketCode:           "TN_SET_HANDICAP",
			MarketName:           "Set Handicap",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainSets,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              3,
			MarketCode:           "TN_CORRECT_SET_SCORE",
			MarketName:           "Correct Set Score",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainSets,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			Status:               MarketStatusActive,
		},

		// --------------------------------------------------------------------
		// 4. ICE HOCKEY (SportID 4)
		// --------------------------------------------------------------------
		{
			SportID:              4,
			MarketCode:           "IH_REGULATION_1X2",
			MarketName:           "Regulation 1X2",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "X", "2"},
			IncludesOvertime:     false,
			IncludesShootout:     false,
			Status:               MarketStatusActive,
		},
		{
			SportID:              4,
			MarketCode:           "IH_MONEYLINE",
			MarketName:           "Moneyline (incl. OT & SO)",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			IncludesOvertime:     true,
			IncludesShootout:     true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              4,
			MarketCode:           "IH_PUCK_LINE",
			MarketName:           "Puck Line (incl. OT)",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			HasLine:              true,
			IncludesOvertime:     true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              4,
			MarketCode:           "IH_TOTAL_GOALS",
			MarketName:           "Total Goals Over/Under",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"OVER", "UNDER"},
			HasLine:              true,
			IncludesOvertime:     true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              4,
			MarketCode:           "IH_PERIOD_1X2",
			MarketName:           "Period 1 Winner",
			Period:               PeriodPeriod1,
			RequiredResultDomain: DomainPeriodScore,
			SettlementTiming:     TimingPeriodEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "X", "2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              4,
			MarketCode:           "IH_PERIOD_TOTALS",
			MarketName:           "Period 1 Total Goals",
			Period:               PeriodPeriod1,
			RequiredResultDomain: DomainPeriodScore,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"OVER", "UNDER"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},

		// --------------------------------------------------------------------
		// 5. VOLLEYBALL (SportID 5)
		// --------------------------------------------------------------------
		{
			SportID:              5,
			MarketCode:           "VB_MATCH_WINNER",
			MarketName:           "Match Winner",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainSets,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              5,
			MarketCode:           "VB_SET_WINNER",
			MarketName:           "Set 1 Winner",
			Period:               PeriodSet1,
			RequiredResultDomain: DomainPeriodScore,
			SettlementTiming:     TimingPeriodEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              5,
			MarketCode:           "VB_TOTAL_POINTS",
			MarketName:           "Total Match Points",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainPoints,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"OVER", "UNDER"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              5,
			MarketCode:           "VB_SET_HANDICAP",
			MarketName:           "Set Handicap",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainSets,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              5,
			MarketCode:           "VB_POINT_HANDICAP",
			MarketName:           "Point Handicap",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainPoints,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              5,
			MarketCode:           "VB_CORRECT_SET_SCORE",
			MarketName:           "Correct Set Score",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainSets,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			Status:               MarketStatusActive,
		},

		// --------------------------------------------------------------------
		// 6. MMA (SportID 6)
		// --------------------------------------------------------------------
		{
			SportID:              6,
			MarketCode:           "MM_FIGHT_WINNER",
			MarketName:           "Fight Winner",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainRounds,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              6,
			MarketCode:           "MM_METHOD_OF_VICTORY",
			MarketName:           "Method Of Victory",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainRounds,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"KO/TKO", "SUBMISSION", "DECISION"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              6,
			MarketCode:           "MM_TOTAL_ROUNDS",
			MarketName:           "Total Rounds Over/Under",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainRounds,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"OVER", "UNDER"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              6,
			MarketCode:           "MM_GOES_DISTANCE",
			MarketName:           "Fight Goes Distance",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainRounds,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"YES", "NO"},
			Status:               MarketStatusActive,
		},

		// --------------------------------------------------------------------
		// 7. RUGBY (SportID 7)
		// --------------------------------------------------------------------
		{
			SportID:              7,
			MarketCode:           "RB_1X2",
			MarketName:           "3-Way Match Result",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "X", "2"},
			IncludesOvertime:     false,
			Status:               MarketStatusActive,
		},
		{
			SportID:              7,
			MarketCode:           "RB_MONEYLINE",
			MarketName:           "Match Winner (incl. ET)",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			IncludesOvertime:     true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              7,
			MarketCode:           "RB_HANDICAP",
			MarketName:           "Handicap",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              7,
			MarketCode:           "RB_TOTAL_POINTS",
			MarketName:           "Total Points Over/Under",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"OVER", "UNDER"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              7,
			MarketCode:           "RB_HT_1X2",
			MarketName:           "Half Time Result",
			Period:               PeriodHalfTime,
			RequiredResultDomain: DomainPeriodScore,
			SettlementTiming:     TimingPeriodEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "X", "2"},
			Status:               MarketStatusActive,
		},

		// --------------------------------------------------------------------
		// 8. CRICKET (SportID 8)
		// --------------------------------------------------------------------
		{
			SportID:              8,
			MarketCode:           "CK_MATCH_WINNER",
			MarketName:           "Match Winner",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              8,
			MarketCode:           "CK_TEAM_RUNS",
			MarketName:           "Team Runs Over/Under",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"OVER", "UNDER"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              8,
			MarketCode:           "CK_MOST_SIXES",
			MarketName:           "Most Sixes",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainTeamStats,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "X", "2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              8,
			MarketCode:           "CK_MOST_FOURS",
			MarketName:           "Most Fours",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainTeamStats,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "X", "2"},
			Status:               MarketStatusActive,
		},

		// --------------------------------------------------------------------
		// 9. AMERICAN FOOTBALL (SportID 9)
		// --------------------------------------------------------------------
		{
			SportID:              9,
			MarketCode:           "AF_MONEYLINE",
			MarketName:           "Moneyline (incl. OT)",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			IncludesOvertime:     true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              9,
			MarketCode:           "AF_SPREAD",
			MarketName:           "Spread (incl. OT)",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			HasLine:              true,
			IncludesOvertime:     true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              9,
			MarketCode:           "AF_TOTAL_POINTS",
			MarketName:           "Total Points (incl. OT)",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"OVER", "UNDER"},
			HasLine:              true,
			IncludesOvertime:     true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              9,
			MarketCode:           "AF_QUARTER_WINNER",
			MarketName:           "Q1 Winner",
			Period:               PeriodQuarter1,
			RequiredResultDomain: DomainPeriodScore,
			SettlementTiming:     TimingPeriodEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			Status:               MarketStatusActive,
		},

		// --------------------------------------------------------------------
		// 10. HANDBALL (SportID 10)
		// --------------------------------------------------------------------
		{
			SportID:              10,
			MarketCode:           "HB_1X2",
			MarketName:           "1X2 / Match Result",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "X", "2"},
			IncludesOvertime:     false,
			Status:               MarketStatusActive,
		},
		{
			SportID:              10,
			MarketCode:           "HB_MONEYLINE",
			MarketName:           "Moneyline",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              10,
			MarketCode:           "HB_HANDICAP",
			MarketName:           "Handicap",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              10,
			MarketCode:           "HB_TOTAL_GOALS",
			MarketName:           "Total Goals Over/Under",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainScore,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"OVER", "UNDER"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              10,
			MarketCode:           "HB_HT_1X2",
			MarketName:           "Half Time Result",
			Period:               PeriodHalfTime,
			RequiredResultDomain: DomainPeriodScore,
			SettlementTiming:     TimingPeriodEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "X", "2"},
			Status:               MarketStatusActive,
		},

		// --------------------------------------------------------------------
		// 11. BASEBALL (SportID 11)
		// --------------------------------------------------------------------
		{
			SportID:              11,
			MarketCode:           "BS_MONEYLINE",
			MarketName:           "Moneyline (incl. extra innings)",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainInnings,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			IncludesOvertime:     true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              11,
			MarketCode:           "BS_RUN_LINE",
			MarketName:           "Run Line (incl. extra innings)",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainInnings,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			HasLine:              true,
			IncludesOvertime:     true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              11,
			MarketCode:           "BS_TOTAL_RUNS",
			MarketName:           "Total Runs Over/Under",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainInnings,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"OVER", "UNDER"},
			HasLine:              true,
			IncludesOvertime:     true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              11,
			MarketCode:           "BS_F5_MONEYLINE",
			MarketName:           "First 5 Innings Winner",
			Period:               "F5",
			RequiredResultDomain: DomainInnings,
			SettlementTiming:     TimingPeriodEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			Status:               MarketStatusActive,
		},

		// --------------------------------------------------------------------
		// 13. TABLE TENNIS (SportID 13)
		// --------------------------------------------------------------------
		{
			SportID:              13,
			MarketCode:           "TT_MATCH_WINNER",
			MarketName:           "Match Winner",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainGames,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              13,
			MarketCode:           "TT_GAME_WINNER",
			MarketName:           "Game 1 Winner",
			Period:               "GAME1",
			RequiredResultDomain: DomainPoints,
			SettlementTiming:     TimingPeriodEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			Status:               MarketStatusActive,
		},
		{
			SportID:              13,
			MarketCode:           "TT_TOTAL_POINTS",
			MarketName:           "Total Match Points",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainPoints,
			SettlementTiming:     TimingInstantIrreversible,
			RuleVersion:          1,
			SupportedSelections:  []string{"OVER", "UNDER"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              13,
			MarketCode:           "TT_POINT_HANDICAP",
			MarketName:           "Point Handicap",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainPoints,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              13,
			MarketCode:           "TT_GAME_HANDICAP",
			MarketName:           "Game Handicap",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainGames,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			SupportedSelections:  []string{"1", "2"},
			HasLine:              true,
			Status:               MarketStatusActive,
		},
		{
			SportID:              13,
			MarketCode:           "TT_CORRECT_SCORE",
			MarketName:           "Correct Game Score",
			Period:               PeriodFullTime,
			RequiredResultDomain: DomainGames,
			SettlementTiming:     TimingEventEnd,
			RuleVersion:          1,
			Status:               MarketStatusActive,
		},
	}

	for _, d := range defs {
		RegisterDefinition(d)
	}
}

func defKey(sportID int, marketCode, period string) string {
	return strconv.Itoa(sportID) + ":" + strings.ToUpper(strings.TrimSpace(marketCode)) + ":" + strings.ToUpper(strings.TrimSpace(period))
}

// RegisterDefinition registers a canonical market definition.
func RegisterDefinition(def MarketDefinition) {
	catalogueMu.Lock()
	defer catalogueMu.Unlock()
	catalogue[defKey(def.SportID, def.MarketCode, def.Period)] = def
}

// GetMarketDefinition finds a market definition.
func GetMarketDefinition(sportID int, marketCode, period string) (MarketDefinition, bool) {
	catalogueMu.RLock()
	defer catalogueMu.RUnlock()
	if period == "" {
		period = PeriodFullTime
	}
	def, ok := catalogue[defKey(sportID, marketCode, period)]
	return def, ok
}

// IsMarketSupported returns true only if the market exists and has an active canonical definition with a rule.
func IsMarketSupported(sportID int, marketCode, period string) bool {
	def, ok := GetMarketDefinition(sportID, marketCode, period)
	if !ok || def.Status != MarketStatusActive {
		return false
	}
	// Check if settlement rule exists in registry
	_, hasRule := Get(sportID, marketCode, period, def.RuleVersion)
	return hasRule
}

// ListAllMarketDefinitions returns all canonical market definitions.
func ListAllMarketDefinitions() []MarketDefinition {
	catalogueMu.RLock()
	defer catalogueMu.RUnlock()
	list := make([]MarketDefinition, 0, len(catalogue))
	for _, d := range catalogue {
		list = append(list, d)
	}
	return list
}
